### ISSUE TITLE
forFeature does not work properly

### ISSUE THREAD

**Issue by mailok** [amcdnl/ngxs#105]
hi!, this is my problem:

in my module:
```
imports: [
    NgxsModule.forFeature([
      ZooState
    ])
  ],
```

this is my state
```
export interface ZooStateModel {
  feed: boolean;
  childres: number[];
}

@State<ZooStateModel>({
  name: 'animals',
  defaults: {
    feed: true,
    childres: [1, 2, 3]
  }
})

export class ZooState {

  @Selector()
  static getFeed(state: ZooStateModel) {
    return state.feed;
  }

  @Action(FeedAnimals)
  feedAnimals({getState, setState}: StateContext<ZooStateModel>, {payload}: FeedAnimals) {
    const state = getState();
    setState({
      ...state,
      feed: payload.data
    });
  }
}

```
and use getFeed in my component

```
@Select(state => state.animals.feed)  feed$: Observable<boolean>;
```
**but the browser console displays the image attached.**

![a](https://user-images.githubusercontent.com/3769277/37655921-f267ed26-2c1c-11e8-8e0a-c2f67ac457f9.PNG)

I then wrote in my AppModule

```
imports: [
    ZooModule,
    NgxsModule.forRoot([])
  ]
```

but still gives me the same error in the browser console,
only it works well when instead of using

```
imports: [
    NgxsModule.forFeature([
      ZooState
    ])
  ],
```
use this:
```
imports: [
    NgxsModule.forRoot([
      ZooState
    ])
  ],
```
any suggestions?

**Comment by deebloo** [comment]
ATM for feature is o it for lazy loaded modules. We are looking to address

**Comment by mailok** [comment]
in the example my module'm still not charging for any route,  I'll do lazy have if it works

**Comment by mailok** [comment]
I tried routing my module and works perfectly!!
Thank you
