### ISSUE TITLE
missing NgxsReduxDevtoolsPluginModule?

### ISSUE THREAD

**Issue by mailok** [amcdnl/ngxs#106]
In the latest version available 2.0.0-rc.9 missing NgxsReduxDevtoolsPluginModule,
but in this documentation https://amcdnl.gitbooks.io/ngxs/plugins/devtools.html 
tells me about this plugin

**Comment by deebloo** [comment]
@mailok check if it is just ReduxDevtoolsPluginModule. the release with that change has not been cut yet
