### ISSUE TITLE
Type actions

### ISSUE THREAD

**Issue by mailok** [amcdnl/ngxs#107]
Is there any way to put a type of actions?
for in Devtools extension show me the actions by feature:

```
[ADMIN] Delete user
[DASHBOARD] Get items
```

**Comment by Silthus** [comment]
You can simply define a `readonly type` property, like so:

```
export class SomeAction {
 readonly type = '[Foo] Some';
}
```

**Comment by mailok** [comment]
Thank you

**Comment by mailok** [comment]
I tried it but does not work, I took the example of ngxs-master and I added:


```
export class AddTodo {
  readonly type = '[Foo] Some';
  constructor(public readonly payload: string) {}
}
```

but still showing the name of the action wrong.

![captura](https://user-images.githubusercontent.com/3769277/37666434-e7104ce8-2c35-11e8-855a-9a64dfe492de.PNG)

**Comment by deebloo** [comment]
@mailok I am confused what you are trying to do? it shows the name of the action class which is correct

**Comment by mailok** [comment]
I want to show me in DevTools
```
[Foo] Some
```

**Comment by amcdnl** [comment]
You have to make it static

**Comment by mailok** [comment]
Now it works!!
Congratulations !!, I love ngxs
