### ISSUE TITLE
Payload not shown using NgxsLoggerPluginModule

### ISSUE THREAD

**Issue by mailok** [amcdnl/ngxs#110]
I wish the payload will be displayed in the console when i use the plugin NgxsLoggerPluginModule.

![captura](https://user-images.githubusercontent.com/3769277/37675412-918a4a10-2c4b-11e8-8ace-da6833c03ddd.PNG)

**Comment by amcdnl** [comment]
Maybe I'm confused but isn't that what that object is?

**Comment by mailok** [comment]
What happens is that the action had a payload, and the payload is not being displayed in the log
