### ISSUE TITLE
Async Actions and NgxsLocalStoragePluginModule

### ISSUE THREAD

**Issue by mailok** [amcdnl/ngxs#112]
hi!, i have the acction:

```
@Action(SearchPeoples)
  serarchPeoples({getState, setState}: StateContext<ParkStateModel>) {
    const state = getState();
    this.http.get<Search>('https://randomuser.me/api/?results=5').subscribe(value => {
      setState({
        ...state,
        search: value.results
      });
    });
  }
```

but when I get the result is not saved in the localStorage, then when I dispact another action, saves the previous result.

my configuration NgxsLocalStoragePluginModule is:

```
 NgxsLocalStoragePluginModule.forRoot({
      key: '@@STATE',
      storage: localStorage,
      deserialize: JSON.parse,
      serialize: JSON.stringify,
    }),
```

**Comment by amcdnl** [comment]
I believe #111 is the same issue. closing as dupe

**Comment by yarrgh** [comment]
That mostly fixed it. However, this doesn't fix subscribing to the observable returned from `Store.dispatch()`. If you subscribe to that observable, it causes the action to be dispatched again.
