### ISSUE TITLE
stackblitz counter is not working for me in chrome

### ISSUE THREAD

**Issue by crh225** [amcdnl/ngxs#113]
stackblitz counter is not working for me in chrome or IE

I went to https://ngxs-simple.stackblitz.io/

clicked the button, and do not see any numbers incrementing. It is hitting the action.

**Comment by yarrgh** [comment]
This is because the state `name` is required. The demo doesn't yet provide the name in the `AppState`.

Should be:
```typescript
@State({
  name: 'app',
  defaults: {
    count: 0
  }
})
export class AppState {
  @Action(Add)
  add({ getState, setState }) {
    const state = getState();
    setState({ count: state.count + 1 });
  }
}
```

**Comment by amcdnl** [comment]
Fixed.
