### ISSUE TITLE
Subscribing to Store.dispatch() causes new action to be dispatched

### ISSUE THREAD

**Issue by yarrgh** [amcdnl/ngxs#114]
All subscriptions to the observable returned from `Store.dispatch()` causes a new action to be dispatched.

Consider the following:
```typescript
onCreate() {
  this.store.dispatch(new CreateAction()).subscribe(res => {
    // do something
  };
}
```

This causes CreateAction to be dispatched twice.

**Comment by deebloo** [comment]
@yarrgh which version were you using when you saw this?

**Comment by yarrgh** [comment]
I thought I was using 2.0.0-rc.11. I've removed node_modules and reinstalled 2.0.0-rc.12 and it seems to be working now. Something must not have updated correctly on my end.
