### ISSUE TITLE
Composing @Selectors

### ISSUE THREAD

**Issue by BeaveArony** [amcdnl/ngxs#117]
When dealing with nested objects the redux documentation strongly suggests to normalize the state as much as possible.
In the docs about sub states you have a cart with items and a saved state with items. In a real world app those items are probably in some sibling shop-item state to cart and are just referenced by id and not actually stored as objects in sub states (children). 
So let's say we did normalize it and want to select a list of items from the cart, how and where could we compose several memoized selectors?
In this example: Select all item-ids from the cart state and map them to the items from the shop state and maybe filter them by availability or something in that vein.
Do we need to create a parent state (to shop and cart) to get access the child states?
With the reselect library we rely on that quite heavily in our projects. Build a selector out of other selectors, no matter where they are located.

**Comment by deebloo** [comment]
@BeaveArony at the moment I think you are correct and yes you would have to create a parent state and write the selector from there. (This is of course when you want )

```TS
@State({
  name: 'root',
  children: [ItemsState, SelectedItemsState]
})
class CartState {
  @Selector() static SelectSomething() {}
}
```

**Comment by amcdnl** [comment]
@BeaveArony - This is great item for docs, would you mind PRn that?

**Comment by markwhitfeld** [comment]
@BeaveArony There is a discussion around selectors here #386
If you have a chance, please read through and add your votes.
In particular you may be interested in the concept of Query classes.
