### ISSUE TITLE
Will libs like redux-persist be possible?

### ISSUE THREAD

**Issue by BeaveArony** [amcdnl/ngxs#118]
I love redux-persist. You wrap the store with it, define blacklists or whitelists, use different storage adapters and on app start the data gets rehydrated automatically for you.
I think it goes beyond the ngxs plugin system which seems like only hooks into the stream of actions like typical redux middleware.
Libs like this would need to be able to hook into the store creation process and define their own sub stores.
Do you think this will be possible to do? Maybe even possible to just use libs like these in the future of ngxs without porting them over?

**Comment by amcdnl** [comment]
Absolutely, we even plan to support Redux middleware w/ an adapter. Just hasn't been a priority, I wasn't even sure if people would want it. Thanks for mentioning this! I'll track this with the Redux Adapter so closing this.
