### ISSUE TITLE
forRoot plugins won't work with AoT

### ISSUE THREAD

**Issue by amcdnl** [amcdnl/ngxs#16]
I don't think having plugins that call methods to pass options will work with AoT.

**Comment by deebloo** [comment]
@amcdnl I added a PR for a demo app. we could potentially use that to test a lot of these senarios

**Comment by deebloo** [comment]
@amcdnl now that the scaffolding is place we can add a test for this

**Comment by amcdnl** [comment]
Just as expected -> 

```
ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'LocalStoragePlugin' was called.
```

**Comment by deebloo** [comment]
I can help trouble shoot this week

**Comment by deebloo** [comment]
example of where plugins could evolve
https://stackblitz.com/edit/test-plugin

**Comment by amcdnl** [comment]
Thats what i was thinking too. I was tinkering with this last night. The plugins array actually gets tranposed into providers so we can just pass the options there.

**Comment by amcdnl** [comment]
Idea ->

```
Ngxs.forRoot([MyStore], {
  plugins: [MyPlugin],
  pluginOptions: [{}]
})
```

**Comment by deebloo** [comment]
I think that is at least a staring point for the API

**Comment by deebloo** [comment]
@amcdnl actually. the more I think about it, I don't think that will work. I think we will have to do this the way http interceptors handles it and I think individual plugins should be responsible for defining how options are passed to them

**Comment by amcdnl** [comment]
Ok but how would I configure an out of the box plugin? Sounds like this solution you’d have to extend the plugin which is kinda nasty

**Comment by deebloo** [comment]
Not at all. The plugin author would have to provide and injection token for config options

**Comment by amcdnl** [comment]
Can you show an example of passing plugins to a out-of-the-box plugin?

**Comment by deebloo** [comment]
Yes

**Comment by deebloo** [comment]
@amcdnl actually the example I posted shows what I am thinking. you probably won't like the API but I think we should focus on making it work first

**Comment by amcdnl** [comment]
They have a plugin system, might be worth checking out - https://github.com/SebastianM/tinystate

**Comment by deebloo** [comment]
I think k they actually do what I was suggesting

**Comment by abalad** [comment]
I use Sebastima's Gmaps, I like it very much. You will not give more support to your @amcdnl ?

**Comment by deebloo** [comment]
@amcdnl yeah they are defining a plugin as a module and using DI to set configs. which I believe you had suggested

**Comment by deebloo** [comment]
@amcdnl update stack blitz to show what I think
