### ISSUE TITLE
Select fn support decorator features

### ISSUE THREAD

**Issue by amcdnl** [amcdnl/ngxs#19]
Make the `ngxs.select` support similar options as the decorator.

**Comment by deebloo** [comment]
@amcdnl would it be possible for `@Select` to also accept the store class?

```TS
@Select(MyStore)
```

**Comment by amcdnl** [comment]
ooooooo- i like it

**Comment by deebloo** [comment]
@amcdnl I think it would be a good way for simple selectors to work. and maybe other selectors can be identified in the Store decorator

**Comment by amcdnl** [comment]
@deebloo - example?

**Comment by Silthus** [comment]
It would be great if passing the State class to the `@Select(FooState)` would try to fetch a slice of the state based on the property name.

Let’s take this example state:

```
StateModel {
 foo: string;
 bar: RandomModel;
}

@State<StateModel>()
class ExampleState {}
```

It would be awesome if something like this would work in my component.

```
@Select(ExampleState)
foo$: Observable<string>;

@Select(ExampleState)
bar$: Observable<RandomObject>;
```

**Comment by amcdnl** [comment]
Interesting. Its tricky w/ name inference because of minification. I will def look into this though.
