### ISSUE TITLE
Initializing the Store redux-devtools with the defaults at application start

### ISSUE THREAD

**Issue by st-clair-clarke** [amcdnl/ngxs#30]
Hi,
Given the store 

```
@Store({
  defaults: {
    feed: false,
    animals: []
  }
})
export class ZooStore {}
```

What is the recommended way letting the store appear in redux-devtool at application start. Currently I see an '@@INIT' in the devtool. 

Cheers

**Comment by amcdnl** [comment]
This should be happening if you include the dev tools plugin.

**Comment by amcdnl** [comment]
I believe this is working now. Please let me know if otherwise
