### ISSUE TITLE
Allow select typed ?

### ISSUE THREAD

**Issue by abalad** [amcdnl/ngxs#40]
Is there a way to pass the state type to Select? 

 // Also accepts a function like our select method
`  @Select(state => state.animals) animals$: Observable<string[]>;`
as 
`  @Select(state<StateType> => state.animals) animals$: Observable<string[]>;`

**Comment by deebloo** [comment]
@abalad adding better type safety is something I am working on. Not sure how we will handle it for the select decorator but we shall see

**Comment by amcdnl** [comment]
Dupe of #25
