### ISSUE TITLE
creating feature stores

### ISSUE THREAD

**Issue by st-clair-clarke** [amcdnl/ngxs#43]
Hi,
I have a clerking and a registration feature.

// clerking
import { Store } from 'ngxs';

@Store({
  defaults: {
    feed: false,
    animals: []
  }
})
export class ClerkingStore {}

// registration
import { Store } from 'ngxs';

@Store({
  defaults: {
    present: false,
    noShow: false
  }
})
export class RegistrationStore {}

What do I need to do to create feature stores instead of a single store.

Maybe you could include it in the documentation under the subheading 'Creating Feature Store'

Thanks

**Comment by amcdnl** [comment]
Feature stores are still in the works so they are not heavily documented.
