### ISSUE TITLE
Where should @Mutations live in a multi-module application

### ISSUE THREAD

**Issue by st-clair-clarke** [amcdnl/ngxs#44]
Hi,
According to your style guide events can be in a separate folder from the store folder.

Given,
import { Store, Mutation } from 'ngxs';

@Store({
  defaults: {
    feed: false,
    animals: []
  }
})
export class ZooStore {
  @Mutation(FeedAnimals)
  feedAnimals(state, { payload }) {
    state.feed = true;
  }
}

Where do you recommend mutations live? In an enterprise level application with different modules, the ZooStore can be cluttered quite rapidly if all Mutations live in the Store class.

Cheer

**Comment by amcdnl** [comment]
If you have a insanely large store, I'd recommend you re-evaluate your state model in that case and break it down into smaller pieces.

**Comment by st-clair-clarke** [comment]
Are you implying that the only place to put the Mutation is in the Store class?
