### ISSUE TITLE
Custom localStorage options

### ISSUE THREAD

**Issue by un33k** [amcdnl/ngxs#47]
[x] enhancement

Allow localStorage to be passed in as an option.

This is great for the mobile environments (native script) where there is no localStorage.

Any option that provides setItem() and getItem() should do.

**Comment by amcdnl** [comment]
Added the ability to set session storage. Does that satisfy your requirements?

**Comment by un33k** [comment]
@amcdnl Looks great!

Would it be possible to extend the storage to take storage engine as an option.

Requirements:
1. Web (browser) application (window.localStorage)
2. Mobile (NativeScript) application (No native localStorage. Support via third-party) 
3. Desktop (Electron) application (window.localStorage via node/Chrome)

It would be great to pass the desired engine in.

With that said, how the engine is passed in is important.  For companies that have their web, mobile and desktop application sharing the same project, the the target platform type can be set in environment/environment.ts.

```
// environment/environment.ts (web portal)
export const environment = {
  production: false,
  storage: window.localStorage
};
```

```
// environment/environment.ts (mobile app - iOS/Android via NativeScript)
import { storageEngine } from 'some-third-party-lib';
export const environment = {
  production: false,
  storage: storageEngine
};
```
```
// environment/environment.ts (desktop)
export const environment = {
  production: false,
  storage: window.localStorage
};
```

It is easy to pass the env.engine to a service via an optional argument.

It is more problematic when storage engine is required in a utility function in a shared app that resides outside of the three apps.

apps/
  - web/app/environment/environment.ts
  - mobile/app/environment/environment.ts
  - desktop/app/environment/environment.ts

libs/
  - auth/auth.service.ts (env/engine passed in via .forRoot(options))
  - auth/auth.utils.ts (how this utility file gets access to the engine?) *hard to do cleanly

**Comment by deebloo** [comment]
@un33k I think that makes sense. we could provide a "NgxsStorage" class and allow you to pass your own storage implementation.

**Comment by deebloo** [comment]
@un33k I have a branch i am working on a potential solution. May submit a PR shortly just to get some feedback

**Comment by un33k** [comment]
How about we just pass in the storage engine.

```typescript
import { NgxsModule, LocalStoragePluginModule, StorageStrategy } from 'ngxs';

@NgModule({
  imports: [
    NgxsModule.forRoot([]),
    LocalStoragePluginModule.forRoot(
      // Default, you can pass single string or array of strings
      // that could be deeply nested too
      key: '@@STATE',
      // Custom serializer, defaults to JSON
      serialize: JSON.stringify,
      // Local storage or session storage strategy
      storageEngine: window.localStorage,  // <---- here
      // Custom deserializer, defaults to JSON
      deserialize: JSON.parse
    )
  ]
})
export class MyModule {}
```

**Comment by amcdnl** [comment]
Done in 2.0
