### ISSUE TITLE
Splitting a large state model into smaller features using  NgxsModule.forFeature( store) mechanism

### ISSUE THREAD

**Issue by st-clair-clarke** [amcdnl/ngxs#49]
Hi,
This is a follow-up to a previous post by by at https://github.com/amcdnl/ngxs/issues/44[](https://github.com/amcdnl/ngxs/issues/44)

How do I breakup a large state model into smaller pieces using  NgxsModule.forFeature( store) mechanism instead of  NgxsModule.forRoot( store) mechanism?

Thanks

**Comment by st-clair-clarke** [comment]
Thanks. Appreciate it.

**Comment by amcdnl** [comment]
I bet he is referring to something like this: https://gist.github.com/amcdnl/6998c0dbad7af5f424dc7719527f9fb8

**Comment by amcdnl** [comment]
#53 Addresses this. gonna close this in favor of that.
