### ISSUE TITLE
Merge Action and Mutation

### ISSUE THREAD

**Issue by deebloo** [amcdnl/ngxs#50]
ATM if you want to do anything async you need to use both and Action and Mutation where the Action will return a new event that triggers a mutation. To me this seems like an unnecessary step. Ngxs already has the ability to handle returning either a raw value, Observable or Promise so I propose we just have Action and that instead of returning an event an action method just returns the new state.

The proposed API would look something like this. Notice that the action methods always resolve in the new state. There are some situations I want to make sure this can handle but thought it would be a good place to start the discussion. One of the things that I would want to solve for is being notified when a particular action is complete. My initial thought is the dispatch method could return an observable that resolves when the action is complete

<img width="651" alt="screen shot 2018-03-06 at 10 34 46 pm" src="https://user-images.githubusercontent.com/6563621/37096179-ce4c7dee-21e5-11e8-84c6-c057a7d03295.png">

**Comment by amcdnl** [comment]
Consider the following:

```
export class TodoStore {
    @Action(AddTodo)
    addTodo(state, { payload }: AddTodo) {
        state.loading = true;
        return todoService.add(payload).pipe(
            map((res) => {
                // If another action ran while this was happening
                // that added a todo, state would be stale in this case
                // thats why dispatching another action is always a snapshot
                // of the new state for that item
                state.todos = [...res];
            )
        })
    }
}
```

**Comment by deebloo** [comment]
I would want to REQURE all Action methods return something

**Comment by amcdnl** [comment]
The dispatch already returns an observable. :)

Why would we have to require it return something? :(

**Comment by deebloo** [comment]
it is more predictable. in my opinion if we allow `state.loading = true;` it might as well just have the value stored locally in the class

**Comment by amcdnl** [comment]
Ya, but its boilerplate.

I don't agree w/ it should be stored in the class. There is many cases where you need flags like this to prevent actions or actions being highly decoupled from emit time and reaction.

**Comment by deebloo** [comment]
I'm not saying I want to do that (I don't) but i do stronly thing you should have to return the new state

**Comment by deebloo** [comment]
Really the thing I want to avoid is anyone asking "why wouldn't I just call the methods myself"

**Comment by amcdnl** [comment]
Well thats one down side to this approach w/ classes, we can't prevent them from doing that.

**Comment by amcdnl** [comment]
We could get clever and do a AOP style hook to throw an error if they tried to call it like that.

**Comment by deebloo** [comment]
@amcdnl still not sure how to account for the stale data situation you mentioned.

**Comment by amcdnl** [comment]
You would need something like `getState()` function to return you the data.

```
export class TodoStore {
    // idea -> would require inheritance
    addTodo(state, action) { 
         const newState = this.getState();
     }

   // idea -> might be awk
   addTodo(getState, action) { 
         const newState = getState();
     }

    /// idea -> feels odd
      addTodo({ state, getState }, action) { 
         const newState = getState();
     }

    /// idea -> callback?
    addTodo(state, action, next) { 
        this.service.get().subscribe((s) => {
            return next((state) => //do something
        })
     }

    /// idea -> they could always just get their state from a select they define
    addTodo(state, action, next) {
        this.service.get().pipe(map(() => this.state$.pipe(take(1))).subscribe(() => {}));
    }
}
```

I think the overall idea might be to support both ways and then show them how they 'might' combine them using a select to get the next state after the callback?

**Comment by deebloo** [comment]
what if the first argument was was an object. that contained a getState and a setState method?

```TS
export class TodoStore {
  addTodo(state, action) { 
    const currentState = state.getState();

    state.setState([action.payload, ...currentState])
  }
}
```

**Comment by amcdnl** [comment]
Hmmm .... that sounds interesting.

**Comment by amcdnl** [comment]
Example API: https://gist.github.com/amcdnl/7da301e4163c230680a6c61e76d787e4

**Comment by tsawan** [comment]
I've gone through this discussion and the gist.
As an outsider who just went through the docs. and the api yesterday, I think the original api is good. 
There may be ways to combine action and mutation but the ones mentioned in this thread are certainly not elegant. Although I picked up this library mainly due to lack of boilerplate required by ngrx, I think some boilerplate may be necessary to keep the api clean.

**Comment by deebloo** [comment]
@tsawan I am actually thinking you may be correct. If we did this incorrectly we could complicate the simple part of the API

**Comment by amcdnl** [comment]
If we were to use inheritance, we could make a global state object

```
class ZooStore extends BaseStore<ZooState> {
   state: ZooState = {};

   @Action(Feed)
   feed({ payload }) {
      // state would be constant in all calls
    }
}
```

**Comment by amcdnl** [comment]
I just realized we will have the same issue with `@Action` giving the state. It would encourage ppl use that which could be old state.

**Comment by deebloo** [comment]
@amcdnl how would we merge the event class? we we require payload be the only property set on the event class?

**Comment by amcdnl** [comment]
Not sure I follow

**Comment by deebloo** [comment]
I just want to clarify how this. { state, getState, setState, dispatch, payload } object gets created

**Comment by amcdnl** [comment]
Proposal:

```javascript
@Store<MyStore>({
  defaults: {}
})
export class FooStore {

  @Action(Feed)
  feed({ getState, setState, dispatch }: StateContext<FooStoreState>, { payload }: Feed) {
    let state = getState();
    setState({ ...state, feeding: true });
    return this.feedService.feed(payload).pipe(map((res) => {
      state = getState();
      setState({ ...state, products: res });
      return dispatch(new FeedSuccess());
    }));
  }

  @Action(AddTodo)
  addTodo({ getState, setState }, { payload }) {
    setState([
      ...getState(),
      payload
    ]);
  }

}
```

**Comment by amcdnl** [comment]
Todo: Add action tracking for all items in a sequence.

**Comment by amcdnl** [comment]
One thing we need to think about is how this affects plugins....

Plugins current work like middleware where they can interject before and after the processing of mutations currently. By changing this control flow, it becomes interesting how these will play.

Plugins would need to know how to accept observables as the response from a next action...

```
    const nextState = compose([...plugins, () => {
      // todo: here?
    }])(curState, event);
```

**Comment by amcdnl** [comment]
@deebloo - IF we are going to go w/ a getter for state, why not use a setter too?

**Comment by deebloo** [comment]
@amcdnl modifying an argument will always feel gross to me.

**Comment by maartentibau** [comment]
I might not have the full understanding, but it feels weird to do a `setState` in an `@action`. I personally like the separation of concerns. To me it's clear an `@action` does something that will alter the state via a `@mutation`, but to do it all in an `@action`, it might be a nice feature, but I think it would create more confusion.

I personally don't really see the problem that needs to be solved.

**Comment by deebloo** [comment]
@maartentibau the goal is the try and remove boilerplate. What tends to happen with a service call method, an action, and a mutation is you have duplication API definitions. One for your service call, one for your action and then another for your mutation

**Comment by maartentibau** [comment]
@deebloo I can understand that, on the other hand it makes the code just more readable, because it's more clear if you keep them separate and also (but I'm certainly no expert on this) wouldn't merging those two things together make it less easy to test?

Maybe I haven't got enough knowledge about the whole concept, but to me it doesn't feel right do merge those two things into one.

**Comment by tsawan** [comment]
@deebloo I agree with @maartentibau here. While I didn't like the boilerplate and duplicate APIs, merging mutations and actions is not good to me. Not sure why actions were not called effects. Actually I wrote all actions for a store in a separate .ts file (like I used to do with ngrx effects) only to find out later that doesn't work.

Hope you guys can come up with a better solution to remove boilerplate.

**Comment by amcdnl** [comment]
The great thing about this API is that you can still keep them separate if you like.

I actually disagree with the separation of concerns. They are both doing something to get and update state. Our actions are not like effects where they handle things like dialogs/etc. you can do that with the event stream though.

**Comment by amcdnl** [comment]
I think this is a documentation thing we will need to address.

**Comment by amcdnl** [comment]
Done in 2.0 branch
