### ISSUE TITLE
Ngxs Service Rename

### ISSUE THREAD

**Issue by amcdnl** [amcdnl/ngxs#52]
I personally don't love this naming:

```
constructor(private ngxs: Ngxs) {
   this.ngxs.dispatch(...);
}
```

I'd like to make it `Store` name but then that would conflict with the `@Store()` decorator. Anyone got any ideas?

**Comment by st-clair-clarke** [comment]
Change @Store to @Ngxs or @NgxsStore; then Store would be now available for use.
Albeit it would be a breaking change.

NB. Be mindful though that ngrx/store uses Store too:

constructor(private store: Store<AppState>){
		this.counter = store.select('counter');
	}

Not that it is a major issue but some folks might not like the name clash in to major offerings.

Cheers

**Comment by BeastCode** [comment]
How about:

constructor(private state: State) {
   this.state.dispatch(...);
}

**Comment by st-clair-clarke** [comment]
My only issue with that is this:

A general statement for accessing state is shown below

```
  @Select( state => state.clerking.ui.history.ros.rs.cough )
  protected coughUi$: Observable<IFormState>
```
Now we have a double state

```
  @Select( state =>state. state.clerking.ui.history.ros.rs.cough )
  protected coughUi$: Observable<IFormState>
```
Apart from that I don't see any great issue.

Maybe we could do this:

```
  @Select( appState =>appState. state.clerking.ui.history.ros.rs.cough )
  protected coughUi$: Observable<IFormState>
```
Cheers

**Comment by amcdnl** [comment]
@BeastCode - I thought about State when i started this. After typing it a few times, I didn't quite like it, I don't really like this either tho. I thought about `RootStore` though.

**Comment by amcdnl** [comment]
What about `Gateway`?

**Comment by BeastCode** [comment]
Gateway - An object that encapsulates access to an external system or resource :)

I was trying to find  a synonym for store that would fit, the only thing I found was: Vault

**Comment by amcdnl** [comment]
I got `Gateway` from this - > https://docs.axonframework.org/v/3.1/part3/command-dispatching.html

Could also think about `Dispatcher` `Commander`?

**Comment by abalad** [comment]
```typescript
constructor(private store: StoreService) {
   this.store.dispatch(...);
}
```

**Comment by abalad** [comment]
```typescript
constructor(private commander: Commander) {
   this.commander.dispatch(...);
}

```

**Comment by abalad** [comment]
```typescript
constructor(private dspatcher: Dispatcher) {
   this.dspatcher.dispatch(...);
}
```

**Comment by abalad** [comment]
```typescript
constructor(private gateway: Gateway) {
   this.gateway.dispatch(...);
}
```

**Comment by abalad** [comment]
```typescript
constructor(private state: State) {
    this.state.dispatch(...);
}
```

**Comment by amcdnl** [comment]
Proposal:

```javascript
export interface ZooStateModel {}

@State<ZooStateModel>({
  defaults: {}
})
export class ZooState {
  @Action(Feed)
  feed() {...}
}

export class ZooComponent {
  constructor(private store: Store<T>) {}

  foo() {
    this.store.dispatch(new Feed());
  }
}
````

**Comment by amcdnl** [comment]
Done in next branch.
