### ISSUE TITLE
Sub Stores

### ISSUE THREAD

**Issue by amcdnl** [amcdnl/ngxs#53]
Ability to create stores within stores. https://gist.github.com/amcdnl/6998c0dbad7af5f424dc7719527f9fb8

One idea is to create dot notation with store names like:

```
@Store({
   name: 'cart'
})
export class CartStore{}

@Store({
   name: 'cart.items'
})
export class CartItemsStore {}
```

then you hook it up like:

```
@NgModule({
   imports: [
      NgxsModule.forRoot([CartStore, CartItemsStore])
   ]
})
export class MyModule {}
```

**Comment by Dercetech** [comment]
NgModule misses the providers:[CartStore, CartItemsStore] even though that's not the point here

**Comment by amcdnl** [comment]
You dont have to here, we handle the providers for you automatically.

**Comment by Dercetech** [comment]
Good point

**Comment by Dercetech** [comment]
A more general remark from an ngrx/store guy:
shouldn't the @Store definition doesn't declare a State-like set of propertieS?

**Comment by amcdnl** [comment]
You use `defaults` property to handle this:

```
@Store({
  name: 'foo',
  defaults: { cart: [] }
})
```

**Comment by Dercetech** [comment]
Ok, then I like the idea :)

**Comment by deebloo** [comment]
I like the idea. I still worry about using strings though

**Comment by amcdnl** [comment]
We can't use nested objects like that because we can't traverse them to hook them up as providers in the forRoot/forFeature methods because of AoT tracability.

**Comment by amcdnl** [comment]
This would be cool but not doable.

```
@Store({
   name: 'cart',
   defaults: {
      items: ItemsStore
   }
})
``

**Comment by deebloo** [comment]
Could web make Store a generic as well?
```
@Store<MyStateModel>({
   name: 'cart',
   defaults: {}, // this would adhere to the model passed in
})
```

**Comment by amcdnl** [comment]
I don't follow how you are defining a sub store there

**Comment by deebloo** [comment]
the only thing I am talking about is when you use strings there is no type safety

**Comment by amcdnl** [comment]
This is a tad more verbose but maybe it answers the riddle:

```
@Store<Cart>({
   state: (state) => state.cart,
   defaults: {}
})
export class Cart {}

@Store<CartList>({
   state: (state) => state.cart.list,
   defaults: {}
})
export class CartList {}
```

**Comment by deebloo** [comment]
hmmmmmmm. I is intrigued

**Comment by amcdnl** [comment]
Essentially treating each store state input like a select. I thought it was clever

**Comment by victormejia** [comment]
```js
state: (state) => state.cart,
```

It's not completely obvious from what piece of the state it is getting the `cart`. Is it the app state?

**Comment by tsawan** [comment]
Just to be a bit clear on this, what problem we are trying to solve with sub stores as opposed to having multiple stores are the root level? we should keep in mind that a feature may be lazy loaded / unloaded so it's store (or sub store) may need to be discarded.

**Comment by amcdnl** [comment]
What about this:

```javascript
@Store<Cart>({
   name: 'cart',
   defaults: {},
   children: {
      items: CartList
   }
})
export class Cart {}

@Store<CartList>({
   name: 'list'
   defaults: []
})
export class CartList {}
```

Similar to what vuex does - https://vuex.vuejs.org/en/modules.html

**Comment by amcdnl** [comment]
Proposal:

```javascript
@State<CartState>({
  selector: (state: AppState) => state.cart,
  defaults: {}
})
export class CartState {
  @Action(Checkout)
  checkout() {
    state.checkedout = true;
  }
}

@State<CartItemsState>({
   selector: (state: AppState) => state.cart.items,
   defaults: {
     moo: true
   }
})
export class CartItemsState {
  @Action(AddtoCart)
  addtocart(item) {
    state.push(item);
  }
}
```

**Comment by deebloo** [comment]
@amcdnl if someone doesn't care about substates can we make "selector" optional?

**Comment by amcdnl** [comment]
The parent will need to define the children as well for tracing the dependencies.

```javascript
@State<Foo>({
   defaults: {},
   children: [
      FooChild
   ]
})
export class Foo {}
```

**Comment by tsawan** [comment]
so @state with replace @store?

**Comment by amcdnl** [comment]
No, you will always need the selector .

Yes, the store decorator is renamed to state in the coming 2.0

**Comment by amcdnl** [comment]
Updated proposal:

Proposal:

```javascript
@State<CartState>({
  selector: (state: AppState) => state.cart,
  defaults: {},
  children: [CartItemsState]
})
export class CartState {
  @Action(Checkout)
  checkout() {
    state.checkedout = true;
  }
}

@State<CartItemsState>({
   selector: (state: AppState) => state.cart.items,
   defaults: {
     moo: true
   }
})
export class CartItemsState {
  @Action(AddtoCart)
  addtocart(item) {
    state.push(item);
  }
}
```

This proposal is similar to the above but with the addition of `children` array on the parent. This is required for state dependency resolution. For example, w/o it I would have no way of knowing that `CartItemsState` was associated to `CartState` at runtime and therefore the `selector` would not be able to init correctly.

Note: The `selector` attribute would completely replace `name`.

**Comment by deebloo** [comment]
if we do the children array. do we need the selector? or can we go back to name?

**Comment by amcdnl** [comment]
Ok I got this now.... No selector, so keeping name but adding children. This will look similar to routes so it fits nicely.
