### ISSUE TITLE
Redux Dev Tools shows previous state

### ISSUE THREAD

**Issue by slillo** [amcdnl/ngxs#54]
In Redux Dev Tools the previous state is shown.

Here is an  [example](https://stackblitz.com/edit/ngxs-example-basic)

Here is a [stackoverflow question](https://stackoverflow.com/questions/49114065/ngxs-redux-dev-tools-show-previous-state) with a more detailed explanation of the problem.

**Comment by amcdnl** [comment]
Fixed. Planning to release in next few days.

**Comment by slillo** [comment]
I updated ngxs to 1.5.1 in the [example](https://stackblitz.com/edit/ngxs-example-basic) and changed imports in AppModule as shown in [documentation](https://amcdnl.gitbooks.io/ngxs/content/plugins/devtools.html):

    NgxsModule.forRoot([AppStore]),
    ReduxDevtoolsPluginModule.forRoot({
        disabled: false // Set to true for prod mode
    })

I get the following error:

Error in /turbo_modules/@angular/compiler@5.0.0/bundles/compiler.umd.js (509:34)
Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.
Evaluating main.ts
Booting application

**Comment by amcdnl** [comment]
Ok, i fixed this ( not released yet ) but noticed the latest changes to plugins broke this plugin @deebloo  :(

**Comment by amcdnl** [comment]
Closing since we are tracking that issue on #58
