### ISSUE TITLE
Add SessionStoragePlugin or option in LocalStoragePlugin to use session storage

### ISSUE THREAD

**Issue by perjansson** [amcdnl/ngxs#59]
Create a Plugin that saves the store into SessionStorage. This would give the benefit that the data is cleared when browser sessions ends, which in many cases is good.

**Comment by deebloo** [comment]
Maybe we could come make the local storage plugin more generic and allow you to pass in the getter and setter rather then just the parser

**Comment by amcdnl** [comment]
Added strategy type  in 1.5.1 :)

**Comment by perjansson** [comment]
Marvelous! 15 min from feature request to production. 👌😉

**Comment by amcdnl** [comment]
That sounds like a good tweet!
