### ISSUE TITLE
LoggerPluginModule giving error 

### ISSUE THREAD

**Issue by tsawan** [amcdnl/ngxs#70]
I am trying to use LoggerPluginModule and it works ok as long as I have a single store. Once I add a 2nd store, I start getting the following error (Windows, Angular 5) in both Chrome and IE. Here I've added a second store "WellStore" and it's giving error.

![image001](https://user-images.githubusercontent.com/3263082/37419307-384cf2ca-27c5-11e8-9834-78b3a0e24216.png)

**Comment by amcdnl** [comment]
Can you make a stackblitz demo? Would be really helpful for us

**Comment by perjansson** [comment]
LoggerPluginModule fails for me as well, but in another way.

```
TypeError: Cannot read property 'app' of undefined
    at StoreFactory.invokeEvents (ngxs-api.js:200)
    at Ngxs._dispatch (ngxs-api.js:326)
    at Ngxs.dispatch (ngxs-api.js:311)
```

app.modules.ts config looks like this:
```
NgxsModule.forRoot([AppStore]),
ReduxDevtoolsPluginModule.forRoot({ disabled: isProduction }),
LocalStoragePluginModule.forRoot({
	key: STORAGE_KEY_NGXS_STORE,
	serialize: JSON.stringify,
	strategy: StorageStrategy.sessionStorage,
	deserialize: JSON.parse,
}),
LoggerPluginModule.forRoot({
	logger: console,
	collapsed: true,
}),
```

**Comment by tsawan** [comment]
@amcdnl unfortunately none of jsfiddle or stackblitz work on my office workstation. I tried to move files around and was also getting the bug mentioned by @perjansson above. Not sure if could only be on windows environment as I tried somewhat similar code on osx and it worked ok.

**Comment by amcdnl** [comment]
I think this is the same as #71

**Comment by deebloo** [comment]
@tsawan can you see if you have the same error when using 2.0?

**Comment by deebloo** [comment]
horay!
