### ISSUE TITLE
bug: Action, LazyLoadedModule and LoggerPluginModule

### ISSUE THREAD

**Issue by boulix3** [amcdnl/ngxs#74]
Hello, there is a bug occuring with actions on lazy loaded modules, but only when LoggerPluginModule is imported.

I have tried to make the example as simple as possible : 
The button dispatches an event which is watched by an action.
The action simply dispatches an event which is watched by a mutation.

Stackblitz example : 
https://stackblitz.com/edit/ngxs-lazy-loaded-module?file=main.ts

Repro steps : 
Navigate to the lazy loaded module by clicking on the "toggle component" button
Clicking the "Toggle visibility" button raises an error (action managed on ToggleStore imported with forFeature). 

If we remove the LoggerPluginModule import, everything works fine.

**Comment by deebloo** [comment]
@boulix3 there is a lot of work going on in the "next" branch ill confirm it is still happening there

**Comment by deebloo** [comment]
@boulix3 can you verify if this is still and issue in 2.0?

**Comment by boulix3** [comment]
# @deebloo the issue is fixed thank you!

I've updated my stackblitz example to the latest rc version.

This library was already awesome, and this version is event better!!

**Comment by boulix3** [comment]
I've updated my sample app on stackblitz, it can help understand the new @Action decorator and its parameters.

https://stackblitz.com/edit/ngxs-lazy-loaded-module?file=app%2Fapp.state.ts

```typescript
import {Action, Store,State, StateContext } from 'ngxs';

/**
 * In this example, an "Add" action is dispatched by the component.
 * the addRaiseAnotherAction method is then called and then dipatches a "DoAdd" action.
 * the addPatchState method is then called and patches the state.
 */

export class Add {}
export class DoAdd {}
@State({
  defaults: {
    count: 0
  }
})
export class AppState {
  @Action(DoAdd)
  addPatchState(context:StateContext<any>) {    
    let state = context.getState();
    context.patchState({count:state.count+1});
  }

  @Action(Add)
  addRaiseAnotherAction(context:StateContext<any>){
    context.dispatch(new DoAdd());
  }
}
```
