### ISSUE TITLE
Have to append Store in all selectors (in 2.0)

### ISSUE THREAD

**Issue by tsawan** [amcdnl/ngxs#84]
Just upgraded to v2.0. Now I have to append 'Store' in all selectors.
e.g., instead of @Select('well.listAllWells'), I have to use @Select('wellStore.listAllWells').
I believe appending Store in all selectors is adding boilerplate (the very reason of using ngxs).

**Comment by tsawan** [comment]
I just noticed that if I define my store name explicitly then it works ok. So probably the issue is with default store name not dropping 'Store' suffix.

**Comment by Silthus** [comment]
Try renaming your store classes to state. There was a breaking change regarding the naming convention.

So instead of `FooStore` try `FooState`.

**Comment by tsawan** [comment]
Sorry to miss that out. yes, it's working fine after renaming the stores.

**Comment by amcdnl** [comment]
Sorry about all the renaming! We are gonna deprecate in the future, I figured since it was so new it would be ok for this release.
