### ISSUE TITLE
add a helper function like updateState 

### ISSUE THREAD

**Issue by tsawan** [amcdnl/ngxs#86]
I really liked the simplicity of updating state in pre 2.0 where I only needed to set the property that's updated. Now in 2.0, I have to use setState(...state, ...) for each update.

How about a helper function like updateState that just takes the updated properties?

**Comment by deebloo** [comment]
@tsawan I could potentially see us adding a "patchState" or something like that. good idea.

**Comment by amcdnl** [comment]
Ooooo I like this .... Shouldn't be too hard... Lets try to get it in 2.0 @deebloo

**Comment by amcdnl** [comment]
Done in rc2.
