### ISSUE TITLE
Rename plugin modules to include ngxs prefix

### ISSUE THREAD

**Issue by Silthus** [amcdnl/ngxs#87]
I think it would be a good idea to rename the plugins to have a Ngxs prefix. That would avoid confusion and make it clear what library the modules belong to. For example:

`LoggerPluginModule` —> `NgxsLoggerPluginModule`

**Comment by boulix3** [comment]
Hello,
If this issue is still assignable, i'd like to be assigned to it.

**Comment by amcdnl** [comment]
Go for it!
