### ISSUE TITLE
state is being overwritten

### ISSUE THREAD

**Issue by tsawan** [amcdnl/ngxs#88]
State is being overwritten when multiple actions are dispatched together (as an array). This is happening as I tried to use the new way of calling async service and updating the state simultaneously.

Please see the demo app. check how first string "redux" disappears" when second string "ngxs" is set.
https://stackblitz.com/edit/ngxs-simple-ghp1mx

**Comment by bossqone** [comment]
I did some investigation and I think that problem is with parameter deconstructing.
```ts
@Action(GetIt2)
getIt2({ state, setState }) {
  return Observable.of('ngxs').delay(2500)
  .pipe(tap(data => {
    setState({
      ...state,
      name2: data
    })

  }));
}
```
This piece of code gets transpiled to:
```js
AppState.prototype.getIt2 = function (_a) {
    var state = _a.state, setState = _a.setState;
    return rxjs_1.Observable.of('ngxs').delay(2500)
        .pipe(operators_1.tap(function (data) {
        setState(__assign({}, state, { name2: data }));
    }));
};
```
As you can see, there's an assigment `state = _a.state`. This will trigger lazy `state` getter in `state-factory.ts` and therefore it will "cache" old state:
```ts
invokeActions(getState, setState, dispatch, action): any[] {
  const results = [];

  for (const metadata of this.states) {
    const name = getTypeFromInstance(action);
    const actionMeta = metadata.actions[name];

    if (actionMeta) {
      const stateContext = {
        get state(): any {      // <------------------------------ this getter
          const state = getState();
          return getValue(state, metadata.depth);
        },
        setState(val: any): void {
          let state = { ...getState() };
          state = setValue(state, metadata.depth, val);
          setState(state);
          return state;
        },
        dispatch(actions: any | any[]): Observable<any> {
          return dispatch(actions);
        }
      };

      const result = metadata.instance[actionMeta.fn](stateContext, action);
      if (result) {
        results.push(result);
      }
    }
  }

  return results;
}
```
If you change action definition to this:
```ts
@Action(GetIt2)
getIt2(context) {
  return Observable.of('ngxs').delay(2500)
  .pipe(tap(data => {
    context.setState({
      ...context.state,
      name2: data
    })

  }));
}
```
it will get's transpiled to:
```js
AppState.prototype.getIt2 = function (context) {
    return rxjs_1.Observable.of('ngxs').delay(2500)
        .pipe(operators_1.tap(function (data) {
        context.setState(__assign({}, context.state, { name2: data }));
    }));
};
```
and it will work as expected.

**Comment by deebloo** [comment]
we should be able to at least write a test around this and see if the explicit function works compared to the getter

**Comment by bossqone** [comment]
Here are examples:
- using `get state` getter: https://codepen.io/bossqone/pen/OvbMMg
- using `getState` function: https://codepen.io/bossqone/pen/MVbKKP

**Comment by deebloo** [comment]
@amcdnl what do you think?

**Comment by amcdnl** [comment]
@bossqone - Your my hero for debugging this!

Sadly, I agree, we are gonna have to make it `getState` :(

**Comment by amcdnl** [comment]
Switched to `getState` in 2.0.0-rc.1
