### ISSUE TITLE
Way with Angular DI

### ISSUE THREAD

**Issue by zverbeta** [amcdnl/ngxs#89]
I think this library very simplest way to use redux in angular apps, but what do you think about that method https://www.bennadel.com/blog/3384-providing-services-as-both-a-multi-collection-and-as-an-individual-injectable-in-angular-5-1-0.htm

**Comment by amcdnl** [comment]
This is a DDD pattern from what I can tell which has its own advantages and disadvantages. I started down that path but backed out.
