### ISSUE TITLE
Adding Memoized Selectors

### ISSUE THREAD

**Issue by myspivey** [amcdnl/ngxs#91]
While the current select system is great for small and simple pieces of state, as state becomes more complex Memoized Selectors (https://github.com/reactjs/reselect) have a lot of advantages. These are a staple of our usage in ngrx and something I think many would prefer to see for code cleanliness and reusability. We for example use them to pre-compute a CSV export string based off the retrieval of a list in state. This selector is referenced in several places so having it as a central part of our state model allows it to be cleanly reused everywhere without any ugly copy paste of the logic behind building the csv. Simply select(MyState.selectMyCsvString).

**Comment by amcdnl** [comment]
I think it would be cool to add these on the classes themselves like:

```javascript
@State({ ... })
export class MyState {
    @Selector() items = (state) => state.items;
}
```

You could even make it auto slice state to be the state of MyState in this. Drawback would be substores and the possibility for them being somewhere else in the chain.

**Comment by amcdnl** [comment]
Done! :) See: https://github.com/amcdnl/ngxs/blob/master/docs/concepts/select.md#memoized-selectors

**Comment by zygimantas** [comment]
@amcdnl 
Current implementation (MyState.items) causes tslint validator to raise no-unbound-method rule warnings.
Is there any other way to call memorized selectors without disabling the rule?

**Comment by zygimantas** [comment]
As described here (https://palantir.github.io/tslint/rules/no-unbound-method/), we can use arrow lambda in memorized selector, like this:

```
@Selector() static items = (state) => state.items;
```
but it fails with:

[ts] Unable to resolve signature of property decorator when called as an expression.
