### ISSUE TITLE
Loss of type property on actions in 2.0.0-rc.1 - please make optional instead

### ISSUE THREAD

**Issue by st-clair-clarke** [amcdnl/ngxs#92]
Hi,
I do not think there is much gain by removing the type property from an action. I agree with you about minimising boilerplate but when it impacts on readability of the program, the gain is lost.

Now we will have a huge headache trying to formulate names in a large enterprise application.

I find the type most useful for the description it provides in the Redux UI tool.

Why not allow the type as in previous releases? At least it is optional for those of us who wish to use it.

NB: I agree with you that there are a lot of breaking changes. I hope as you say, things will be deprecated in the future to allow us time for the adjustments in the codebase.

**Comment by deebloo** [comment]
@st-clair-clarke is there anything preventing you from adding a type property to an action?

**Comment by st-clair-clarke** [comment]
I must have misinterpreted the docs @deebloo. From reading it I did not thought it would accepty a type. Thanks for the info as usual. I will try it.
Cheers

**Comment by deebloo** [comment]
@st-clair-clarke unless there is anything else I am going to close this issue as answered
