### ISSUE TITLE
Calling setState in every action feels convoluted

### ISSUE THREAD

**Issue by flore2003** [amcdnl/ngxs#96]
With the new API, updating the state in an `@Action` is done using the `setState` method. This feels quite convoluted in comparison to the old API. Wouldn't it be possible to just return an observable of the new state instead?

For actions that should not modify the state, a special param to the `@Action` decorator could be introduced. Something like `{mutate: false}` maybe.  
Or the action method could just not return anything and this would be interpreted as a non-mutating action.

**Comment by amcdnl** [comment]
We toyed with several different APIs but in the end the most flexible solution was this. It allows the setting of state at various points during the action for more flexibility and less Rx ninja skills required.
